#Dockerfile.backend
FROM golang:1.20-alpine

#Set the working directory
WORKDIR /app

#Copy the mod and sum and download them
COPY backend/go.mod backend/go.sum ./
RUN go mod download

# Copy the backend source code
COPY backend/ .

#Build the application
RUN go build -o main .

#Expose port 8080
EXPOSE 8080

# RUN the executable
CMD ["./main"]